/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "surface-container-highest": "#192540",
          "primary-dim": "#8455ef",
          "inverse-surface": "#faf8ff",
          "tertiary-dim": "#00a7f2",
          "tertiary": "#57bcff",
          "secondary-dim": "#24f07e",
          "on-tertiary": "#003652",
          "secondary-container": "#006d35",
          "on-tertiary-fixed-variant": "#003d5c",
          "primary-container": "#ae8dff",
          "on-error": "#490013",
          "tertiary-fixed": "#4cb9ff",
          "primary": "#ba9eff",
          "on-secondary-fixed-variant": "#006832",
          "surface-container": "#0f1930",
          "on-secondary": "#005d2c",
          "on-surface-variant": "#a3aac4",
          "on-background": "#dee5ff",
          "on-primary-fixed-variant": "#370086",
          "error": "#ff6e84",
          "secondary": "#3fff8b",
          "on-error-container": "#ffb2b9",
          "on-tertiary-container": "#002a42",
          "surface": "#060e20",
          "on-secondary-container": "#e3ffe4",
          "surface-dim": "#060e20",
          "on-primary-fixed": "#000000",
          "surface-container-lowest": "#000000",
          "outline-variant": "#40485d",
          "on-primary": "#39008c",
          "primary-fixed-dim": "#a27cff",
          "on-tertiary-fixed": "#001a2a",
          "primary-fixed": "#ae8dff",
          "outline": "#6d758c",
          "surface-container-low": "#091328",
          "secondary-fixed-dim": "#24f07e",
          "background": "#060e20",
          "surface-bright": "#1f2b49",
          "on-secondary-fixed": "#004820",
          "on-primary-container": "#2b006e",
          "secondary-fixed": "#3fff8b",
          "error-container": "#a70138",
          "surface-container-high": "#141f38",
          "inverse-on-surface": "#4d556b",
          "inverse-primary": "#6e3bd7",
          "tertiary-container": "#00affe",
          "on-surface": "#dee5ff",
          "surface-variant": "#192540",
          "tertiary-fixed-dim": "#00adfa",
          "error-dim": "#d73357",
          "surface-tint": "#ba9eff"
      },
      "borderRadius": {
          "sm": "0.5rem",
          "DEFAULT": "0.75rem",
          "lg": "1rem",
          "xl": "1.25rem",
          "2xl": "1.5rem",
          "full": "9999px"
      },
      "spacing": {
        "px": "1px",
        "0": "0",
        "0.5": "0.125rem",
        "1": "0.25rem",
        "1.5": "0.375rem",
        "2": "0.5rem",
        "3": "0.75rem",
        "4": "1rem",
        "5": "1.25rem",
        "6": "1.5rem",
        "8": "2rem",
        "10": "2.5rem",
        "12": "3rem",
        "16": "4rem",
        "20": "5rem",
        "24": "6rem",
        "32": "8rem",
        "40": "10rem",
        "48": "12rem",
        "56": "14rem",
        "64": "16rem",
      },
      "boxShadow": {
        "premium": "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
        "premium-hover": "0 25px 30px -5px rgba(0, 0, 0, 0.15), 0 15px 15px -5px rgba(0, 0, 0, 0.08)",
        "glass": "0 8px 32px 0 rgba(0, 0, 0, 0.37)",
      },
      "fontFamily": {
          "headline": ["Space Grotesk", "sans-serif"],
          "body": ["Manrope", "sans-serif"],
          "label": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [],
}
