import { useState, useRef, useEffect } from "react";
import { MessageSquare, X, Send, Sparkles, Bot, User, ChevronDown } from "lucide-react";

type Message = { role: "user" | "bot"; text: string; time: string };

const FAQS: { q: string; a: string }[] = [
  { q: "What is FITLOOP?", a: "FITLOOP is an AI-powered clothing fit platform. It uses machine learning to analyze your body measurements, predict how clothes will fit, and reduce return rates for e-commerce platforms." },
  { q: "How does the body scan work?", a: "You can initiate a body scan via camera or by uploading photos. Our ML model extracts 24 key body measurements with up to 96.2% accuracy using computer vision. No special hardware required." },
  { q: "How accurate is the size recommendation?", a: "Our size recommendations have a 96.2% accuracy rate, trained on over 2.8 million body measurement data points across brands and regions." },
  { q: "What is a fit score?", a: "A fit score (0–100) represents how well a specific garment matches your body measurements. Scores above 90 are perfect fits. Below 80, we recommend a different size or style." },
  { q: "How does wardrobe scanning work?", a: "Upload photos of your clothes or capture them via camera. Our clothing detection model identifies each item, categorizes it, extracts attributes (color, type, pattern), and detects duplicates." },
  { q: "What is the Shopping Readiness Score?", a: "The Shopping Readiness Score shows how complete your wardrobe profile is. A higher score means more accurate outfit and fit recommendations when you shop." },
  { q: "How are outfit suggestions generated?", a: "Outfits are generated by our Mix & Match engine which considers your body type, existing wardrobe items, occasion context, color harmony, and brand fit data." },
  { q: "Can I see how a product fits before buying?", a: "Yes! Use the Smart Shopping section's 'Will This Fit Me?' feature. Enter a product URL or SKU and our system will compute a fit confidence score based on your body profile." },
  { q: "What does return risk mean?", a: "Return risk is a prediction of how likely an order is to be returned due to fit issues. High risk orders show fit score below your threshold and trigger alerts so you can intervene early." },
  { q: "Is my body data private?", a: "Yes. All body measurement data is encrypted at rest and in transit. You can configure data retention periods and anonymization settings in the Security tab under Settings." },
];

function matchFAQ(input: string): string | null {
  const lower = input.toLowerCase();
  for (const faq of FAQS) {
    const keywords = faq.q.toLowerCase().split(" ").filter(w => w.length > 3);
    const hits = keywords.filter(k => lower.includes(k)).length;
    if (hits >= 2) return faq.a;
  }
  if (lower.includes("fit") && lower.includes("score")) return FAQS[3].a;
  if (lower.includes("scan") || lower.includes("body")) return FAQS[1].a;
  if (lower.includes("wardrobe")) return FAQS[4].a;
  if (lower.includes("outfit") || lower.includes("suggestion")) return FAQS[6].a;
  if (lower.includes("return")) return FAQS[8].a;
  if (lower.includes("privacy") || lower.includes("data") || lower.includes("secure")) return FAQS[9].a;
  if (lower.includes("size") || lower.includes("recommend")) return FAQS[2].a;
  if (lower.includes("shop") || lower.includes("buy") || lower.includes("purchase")) return FAQS[7].a;
  if (lower.includes("what") && lower.includes("fitloop")) return FAQS[0].a;
  return null;
}

const SUGGESTIONS = [
  "How does body scan work?",
  "What is a fit score?",
  "How are outfits suggested?",
  "Is my data private?",
];

function now() {
  return new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
}

export default function AIChatbot() {
  const [open, setOpen] = useState(false);
  const [input, setInput] = useState("");
  const [typing, setTyping] = useState(false);
  const [messages, setMessages] = useState<Message[]>([
    {
      role: "bot",
      text: "Hi! I'm the FITLOOP AI assistant. Ask me anything about fit scores, body scanning, outfit suggestions, or how our ML engine works.",
      time: now(),
    },
  ]);
  const bottomRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (open) {
      setTimeout(() => inputRef.current?.focus(), 100);
    }
  }, [open]);

  useEffect(() => {
    bottomRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, typing]);

  const send = (text?: string) => {
    const q = (text ?? input).trim();
    if (!q) return;
    setInput("");
    setMessages(m => [...m, { role: "user", text: q, time: now() }]);
    setTyping(true);
    setTimeout(() => {
      const answer = matchFAQ(q) ??
        "I'm best at answering questions about FITLOOP's fit technology, body scanning, outfit suggestions, and shopping features. Could you rephrase, or pick one of the quick questions below?";
      setMessages(m => [...m, { role: "bot", text: answer, time: now() }]);
      setTyping(false);
    }, 800 + Math.random() * 600);
  };

  return (
    <>
      {/* Floating button */}
      <button
        onClick={() => setOpen(o => !o)}
        className="fixed bottom-5 right-5 z-50 w-12 h-12 rounded-full bg-gradient-to-br from-violet-500 to-purple-700 shadow-xl flex items-center justify-center text-white hover:scale-105 transition-transform"
        aria-label="Open AI assistant"
      >
        {open ? <X className="w-5 h-5" /> : <MessageSquare className="w-5 h-5" />}
        {!open && (
          <span className="absolute -top-1 -right-1 w-3.5 h-3.5 bg-green-400 rounded-full border-2 border-white" />
        )}
      </button>

      {/* Chat panel */}
      {open && (
        <div className="fixed bottom-20 right-5 z-50 w-[360px] bg-card border border-border rounded-2xl shadow-2xl flex flex-col overflow-hidden" style={{ height: 500 }}>
          {/* Header */}
          <div className="flex items-center gap-3 px-4 py-3 bg-gradient-to-r from-violet-600 to-purple-700 flex-shrink-0">
            <div className="w-8 h-8 rounded-full bg-white/20 flex items-center justify-center flex-shrink-0">
              <Sparkles className="w-4 h-4 text-white" />
            </div>
            <div className="flex-1">
              <p className="text-white font-semibold text-sm">FITLOOP AI</p>
              <div className="flex items-center gap-1.5">
                <span className="w-1.5 h-1.5 rounded-full bg-green-400" />
                <span className="text-white/70 text-[10px]">Always online</span>
              </div>
            </div>
            <button onClick={() => setOpen(false)} className="w-7 h-7 rounded-lg flex items-center justify-center text-white/70 hover:text-white hover:bg-white/10 transition-colors">
              <ChevronDown className="w-4 h-4" />
            </button>
          </div>

          {/* Messages */}
          <div className="flex-1 overflow-y-auto px-4 py-3 space-y-3">
            {messages.map((m, i) => (
              <div key={i} className={`flex gap-2 ${m.role === "user" ? "flex-row-reverse" : ""}`}>
                <div className={`w-6 h-6 rounded-full flex-shrink-0 flex items-center justify-center mt-0.5 ${m.role === "bot" ? "bg-violet-100 dark:bg-violet-900/40" : "bg-primary"}`}>
                  {m.role === "bot" ? <Bot className="w-3.5 h-3.5 text-violet-600 dark:text-violet-400" /> : <User className="w-3.5 h-3.5 text-white" />}
                </div>
                <div className={`flex flex-col gap-0.5 max-w-[78%] ${m.role === "user" ? "items-end" : ""}`}>
                  <div className={`px-3 py-2 rounded-2xl text-[13px] leading-relaxed ${
                    m.role === "bot"
                      ? "bg-muted text-foreground rounded-tl-sm"
                      : "bg-primary text-primary-foreground rounded-tr-sm"
                  }`}>
                    {m.text}
                  </div>
                  <span className="text-[10px] text-muted-foreground px-1">{m.time}</span>
                </div>
              </div>
            ))}
            {typing && (
              <div className="flex gap-2">
                <div className="w-6 h-6 rounded-full bg-violet-100 dark:bg-violet-900/40 flex items-center justify-center flex-shrink-0 mt-0.5">
                  <Bot className="w-3.5 h-3.5 text-violet-600 dark:text-violet-400" />
                </div>
                <div className="px-3 py-2.5 bg-muted rounded-2xl rounded-tl-sm flex items-center gap-1">
                  {[0,1,2].map(i => (
                    <span key={i} className="w-1.5 h-1.5 rounded-full bg-muted-foreground/50 animate-bounce" style={{ animationDelay: `${i * 0.15}s` }} />
                  ))}
                </div>
              </div>
            )}
            <div ref={bottomRef} />
          </div>

          {/* Suggestions */}
          {messages.length <= 2 && (
            <div className="px-4 pb-2 flex gap-1.5 flex-wrap flex-shrink-0">
              {SUGGESTIONS.map(s => (
                <button
                  key={s}
                  onClick={() => send(s)}
                  className="text-[11px] px-2.5 py-1 bg-accent text-accent-foreground rounded-full border border-border hover:border-primary/40 hover:bg-accent transition-colors"
                >
                  {s}
                </button>
              ))}
            </div>
          )}

          {/* Input */}
          <div className="px-3 pb-3 flex-shrink-0">
            <div className="flex gap-2 bg-muted rounded-xl p-1.5">
              <input
                ref={inputRef}
                value={input}
                onChange={e => setInput(e.target.value)}
                onKeyDown={e => e.key === "Enter" && send()}
                placeholder="Ask about fit, scanning, outfits..."
                className="flex-1 bg-transparent text-[13px] text-foreground placeholder:text-muted-foreground focus:outline-none px-1.5"
              />
              <button
                onClick={() => send()}
                disabled={!input.trim()}
                className="w-8 h-8 rounded-lg bg-primary text-primary-foreground flex items-center justify-center disabled:opacity-40 hover:bg-primary/90 transition-all"
              >
                <Send className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
